version: "3"
services:
  web:
    build: ./Dockerbuild
    image: spark
    ports:
      - "8888:8888"
# Alter path before collon to your work directory outside of docker.
# This volume will be synced inside and out
    volumes:
      - ../../prototipo_painel:/home/jovyan/work
