version: "3"
services:
  master:
    build: ./master
    image: master
    ports:
      - "8080:8080"
    volumes:
      - ./work:/root/work
    stdin_open: true
    tty: true
  slave:
    build: ./slave
    image: slave
    ports:
      - "8081:8080"
    stdin_open: true
    tty: true
